### ISSUE TITLE
# 5 De to spiller skal kunne udvælge et ord, fra tre tilfældige udvalgte ord fra listen af normale ord, eller selv skrive et ord som eksistere på listen. Ordet vil så blive giver til modspilleren 

### ISSUE THREAD

**Issue by AndyDickie** [AndyDickie/Eksamsprojekt#16]
Tidsestimat: 15 timer

**Comment by joha7809** [comment]
Vi valgte istedet at implementere at ordet for de to spillere bliver udvalgt tilfældigt. I fremtiden ville denne feature med at udvælge tre ord dog godt kunne blive implementeret, vi har bare valgt at fokusere på det vigtigste i projektet.
